const fs = require('fs');
const path = require('path');

const indexHtml = fs.readFileSync(path.join(__dirname, 'public', 'index.html'), 'utf-8');

const translations = {
  hi: {
    '<link rel="canonical" href="https://www.wastatusvideo.com"/>': '<link rel="canonical" href="https://www.wastatusvideo.com/hi/"/>',

      "Upload Your Videos": "Apne Videos Upload Karein",
      "Drop Videos Here": "Videos Yahan Drop Karein",
      "or click to browse files": "ya files browse karne ke liye click karein",
      "Max 3 videos · 300MB total · Auto-split into 29s clips!": "Max 3 videos · Total 300MB · 29s clips mein auto-split!",
      "🚀 Compress Videos": "🚀 Videos Compress Karein",
      "Processing Videos...": "Videos Process Ho Rahe Hain...",
      "Starting...": "Start ho raha hai...",
      "Overall Progress": "Overall Progress",
      "Activate on WhatsApp": "WhatsApp Par Activate Karein",
      "Your video was split into <span id=\"clipCount\">?</span> clips — all will be sent to WhatsApp!": "Aapka video <span id=\"clipCount\">?</span> clips mein split ho gaya hai — sabhi WhatsApp par bhej diye jayenge!",
      "Your Activation Code": "Aapka Activation Code",
      "📋 Copy Code": "📋 Code Copy Karein",
      "⏱️ Code expires in:": "⏱️ Code expire hoga:",
      "Send code before timer runs out!": "Timer khatam hone se pehle code bhejein!",
      "❌ Code Expired!": "❌ Code Expire Ho Gaya!",
      "Your 5 minutes are up. Please compress your video again.": "Aapke 5 minute khatam ho gaye hain. Kripya apna video dobara compress karein.",
      "🔄 Start Again": "🔄 Phir Se Start Karein",
      "📋 How it works:": "📋 Yeh kaise kaam karta hai:",
      "Click the button below to <strong>open WhatsApp</strong>": "<strong>WhatsApp open</strong> karne ke liye niche button par click karein",
      "Your activation code is <strong>already typed</strong> in the message": "Aapka activation code message mein <strong>pehle se type</strong> kiya hua hai",
      "Just press <strong>SEND</strong> in WhatsApp": "Bas WhatsApp mein <strong>SEND</strong> dabayein",
      "Receive your <strong>HD video clips</strong> directly in WhatsApp! 🎬": "Apne <strong>HD video clips</strong> seedhe WhatsApp par payein! 🎬",
      "⚠️ <span>Code valid for <strong>5 minutes only!</strong> Send it on WhatsApp before it expires!</span>": "⚠️ <span>Code sirf <strong>5 minute ke liye valid hai!</strong> Expire hone se pehle isse WhatsApp par bhejein!</span>",
      "💚 Activate on WhatsApp": "💚 WhatsApp Par Activate Karein",
      "Almost There! 🚀": "Bas Hone Hi Wala Hai! 🚀",
      "Send the activation code in WhatsApp to receive your videos!": "Apne videos paane ke liye WhatsApp mein activation code bhejein!",
      "Video Sent": "Video Bhej Diya Gaya",
      "Quality\\n              </div>": "Quality\\n              </div>",
      "Delivered\\n              </div>": "Deliver Ho Gaya\\n              </div>",
      "📱 Upload to Status:": "📱 Status Par Upload Karein:",
      "Open <strong>WhatsApp</strong>": "<strong>WhatsApp</strong> Open Karein",
      "Find video from <strong>StatusDrop</strong>": "<strong>StatusDrop</strong> se video find karein",
      "<strong>Tap & hold</strong> the video": "Video ko <strong>Tap & hold</strong> karein",
      "Tap <strong>Forward</strong> →\\n              Select <strong>My Status</strong>": "<strong>Forward</strong> Tap karein →\\n              <strong>My Status</strong> select karein",
      "<strong>Done! 🎉</strong>\\n              Enjoy your HD Status!": "<strong>Ho gaya! 🎉</strong>\\n              Apne HD Status enjoy karein!",
      "🔄 Process More Videos": "🔄 Aur Videos Process Karein",
      "📤 Share App": "📤 App Share Karein",
      "❓ Frequently Asked Questions": "❓ Aksar Pooche Jaane Wale Sawaal",
      "Why is my WhatsApp Status video blurry?": "Mera WhatsApp Status video blur kyun hai?",
      "WhatsApp automatically compresses videos to save bandwidth, which destroys quality. StatusDrop pre-compresses your video to the exact specifications WhatsApp expects, so it stays HD.": "WhatsApp bandwidth bachane ke liye videos ko automatically compress kar deta hai, jisse quality kharab ho jati hai. StatusDrop aapke video ko un exact specifications par pre-compress karta hai jo WhatsApp ko chahiye, isliye yeh HD rehta hai.",
      "WhatsApp automatically destroys video quality to save bandwidth.\n          StatusDrop pre-compresses your video to the exact specs WhatsApp\n          expects — so it stays HD quality when posted as a Status.": "WhatsApp bandwidth bachane ke liye video quality automatically kharab kar deta hai.\n          StatusDrop aapke video ko un exact specs par pre-compress karta hai jo WhatsApp\n          ko chahiye — isliye Status post karne par yeh HD quality mein rehta hai.",
      "How do I upload a long video to WhatsApp Status?": "Main WhatsApp Status par long video kaise upload karun?",
      "WhatsApp Status only allows 29-second videos. StatusDrop automatically splits your long video into multiple 29-second clips and sends them all directly to your WhatsApp for free.": "WhatsApp Status sirf 29-second ke videos allow karta hai. StatusDrop automatically aapke long video ko multiple 29-second clips mein split kar deta hai aur unhe directly aapke WhatsApp par bhejta hai, bilkul free.",
      "WhatsApp Status only allows 29-second videos. StatusDrop\n          automatically splits your long video into multiple 29-second\n          clips and sends them all directly to your WhatsApp — completely free!": "WhatsApp Status sirf 29-second ke videos allow karta hai. StatusDrop\n          automatically aapke long video ko multiple 29-second clips mein\n          split kar deta hai aur un sabhi ko directly aapke WhatsApp par bhejta hai — bilkul free!",
      "Is StatusDrop free to use?": "Kya StatusDrop use karna free hai?",
      "Yes, StatusDrop is completely free. No login, no watermark, no hidden fees. Upload videos up to 300MB and receive them HD quality on WhatsApp.": "Haan, StatusDrop bilkul free hai. Koi login nahi, koi watermark nahi, koi hidden fees nahi. 300MB tak ke videos upload karein aur unhe WhatsApp par HD quality mein receive karein.",
      "Is StatusDrop really free?": "Kya StatusDrop sach mein free hai?",
      "Yes! 100% free. No login, no account, no watermark, no hidden\n          fees. Upload videos up to 300MB and receive them in HD quality\n          directly on WhatsApp.": "Haan! 100% free. Koi login nahi, koi account nahi, koi watermark nahi, koi hidden\n          fees nahi. 300MB tak ke videos upload karein aur unhe directly WhatsApp par\n          HD quality mein receive karein.",
      "What video formats does StatusDrop support?": "StatusDrop kaunse video formats support karta hai?",
      "What video formats are supported?": "Kaunse video formats supported hain?",
      "StatusDrop supports MP4, MOV, AVI, MKV, 3GP and WMV formats up to 300MB in size.": "StatusDrop 300MB tak ke MP4, MOV, AVI, MKV, 3GP aur WMV formats support karta hai.",
      "StatusDrop supports MP4, MOV, AVI, MKV, 3GP and WMV\n          formats up to 300MB in file size.": "StatusDrop 300MB file size tak ke MP4, MOV, AVI, MKV, 3GP aur WMV\n          formats support karta hai.",
      "Is my video private and secure?": "Kya mera video private aur secure hai?",
      "Yes! Your video is automatically deleted from our servers\n          within 5 minutes after being sent to your WhatsApp.\n          We never store or share your videos.": "Haan! Aapke WhatsApp par bheje jaane ke 5 minute ke andar aapka video\n          hamare servers se automatically delete ho jata hai.\n          Hum aapke videos kabhi store ya share nahi karte.",
      "Free HD WhatsApp Status videos.<br/>\n        Compress, split & deliver instantly.": "Free HD WhatsApp Status videos.<br/>\n        Turant compress, split aur deliver karein.",
      "Privacy Policy": "Privacy Policy",
      "🔒 No Account Needed": "🔒 Kisi Account Ki Zaroorat Nahi",
      "🗑️ Auto Deleted in 5 mins": "🗑️ 5 minute mein Auto Delete",
      "📵 No Watermark": "📵 Koi Watermark Nahi",
      "© 2026 StatusDrop · Made with 💚": "© 2026 StatusDrop · 💚 ke sath banaya gaya"
  
  },
  pt: {
    '<html lang="en">': '<html lang="pt">',
    '<link rel="canonical" href="https://www.wastatusvideo.com"/>': '<link rel="canonical" href="https://www.wastatusvideo.com/pt/"/>',
    'WhatsApp Status Video Compressor - Upload HD & Long Videos Free': 'WhatsApp Status Video Compressor - Envie Vídeos Longos e em HD Grátis',
    'Free WhatsApp Status video compressor. Upload HD videos up to 300MB, auto-split long videos into 29-second clips. No blur, no watermark, no login needed. Works worldwide!': "Compressor gratuito de vídeos para o WhatsApp Status. Envie vídeos em HD de até 300MB, divida vídeos longos automaticamente em clipes de 29 segundos. Sem marca d'água.",
    'Stop blurry WhatsApp Status videos! Compress & send HD videos directly to your WhatsApp. Auto-splits long videos. 100% Free, No login needed.': 'Chega de vídeos embaçados no WhatsApp Status! Comprima e envie vídeos em HD direto pro seu WhatsApp. Divide vídeos longos automaticamente. 100% Grátis.',
    'WhatsApp Status Video Compressor - HD Videos Free': 'WhatsApp Status Video Compressor - Vídeos HD Grátis',
    'Stop blurry WhatsApp Status! Compress & send HD videos free. Auto-splits long videos into 29s clips.': 'Chega de Status embaçados! Comprima e envie vídeos em HD grátis. Divide vídeos longos automaticamente em clipes de 29s.',
    'Video Compressor\\n    </h1>': 'Compressor de Vídeo\\n    </h1>',
    'Stop blurry Status videos! Upload HD videos up to 300MB —\\n      auto-split into 29s clips & delivered to your WhatsApp free': 'Chega de Status embaçados! Envie vídeos HD de até 300MB —\\n      divisão automática em clipes de 29s entregues no seu WhatsApp grátis',
    '✅ Free': '✅ Grátis',
    '⚡ Fast': '⚡ Rápido',
    '🔒 Private': '🔒 Privado',
    '✂️ Auto Split': '✂️ Divisão Auto',
    '🌍 Works Worldwide': '🌍 Funciona em todo o mundo',
    'Videos Processed': 'Vídeos Processados',
    'Quality Always': 'Qualidade Sempre',
    'Max Upload': 'Upload Máximo',
    'Always & Forever': 'Sempre e Para Sempre',
    'Auto Split & Compress — Any Size Video!': 'Dividir e Comprimir — Qualquer Tamanho!',
    'Long videos are automatically split into 29-second WhatsApp-ready clips. Upload up to 300MB!': 'Vídeos longos são divididos automaticamente em clipes de 29s pro WhatsApp. Até 300MB!',
    'Upload Your Videos': 'Envie seus Vídeos',
    'Drop Videos Here': 'Solte os Vídeos Aqui',
    'or click to browse files': 'ou clique para procurar arquivos',
    'Max 3 videos · 300MB total · Auto-split into 29s clips!': 'Máx 3 vídeos · Total de 300MB · Divisão auto em 29s!',
    '🚀 Compress Videos': '🚀 Comprimir Vídeos',
    'Processing Videos...': 'Processando Vídeos...',
    'Starting...': 'Iniciando...',
    'Overall Progress': 'Progresso Geral',
    'Activate on WhatsApp': 'Ativar no WhatsApp',
    'Your video was split into <span id="clipCount">?</span> clips — all will be sent to WhatsApp!': 'Seu vídeo foi dividido em <span id="clipCount">?</span> clipes — todos serão enviados pro WhatsApp!',
    'Your Activation Code': 'Seu Código de Ativação',
    '📋 Copy Code': '📋 Copiar Código',
    '⏱️ Code expires in:': '⏱️ O código expira em:',
    'Send code before timer runs out!': 'Envie o código antes que o tempo acabe!',
    '❌ Code Expired!': '❌ Código Expirado!',
    'Your 5 minutes are up. Please compress your video again.': 'Seus 5 minutos acabaram. Por favor, comprima seu vídeo novamente.',
    '🔄 Start Again': '🔄 Começar Novamente',
    '📋 How it works:': '📋 Como funciona:',
    'Click the button below to <strong>open WhatsApp</strong>': 'Clique no botão abaixo para <strong>abrir o WhatsApp</strong>',
    'Your activation code is <strong>already typed</strong> in the message': 'O seu código de ativação <strong>já está digitado</strong> na mensagem',
    'Just press <strong>SEND</strong> in WhatsApp': 'Basta apertar <strong>ENVIAR</strong> no WhatsApp',
    'Receive your <strong>HD video clips</strong> directly in WhatsApp! 🎬': 'Receba seus <strong>clipes de vídeo em HD</strong> diretamente no WhatsApp! 🎬',
    '⚠️ <span>Code valid for <strong>5 minutes only!</strong> Send it on WhatsApp before it expires!</span>': '⚠️ <span>Código válido por <strong>apenas 5 minutos!</strong> Envie no WhatsApp antes que expire!</span>',
    '💚 Activate on WhatsApp': '💚 Ativar no WhatsApp',
    'Almost There! 🚀': 'Quase Lá! 🚀',
    'Send the activation code in WhatsApp to receive your videos!': 'Envie o código de ativação no WhatsApp para receber seus vídeos!',
    'Video Sent': 'Vídeo Enviado',
    'Quality\\n              </div>': 'Qualidade\\n              </div>',
    'Delivered\\n              </div>': 'Entregue\\n              </div>',
    '📱 Upload to Status:': '📱 Enviar para o Status:',
    'Open <strong>WhatsApp</strong>': 'Abra o <strong>WhatsApp</strong>',
    'Find video from <strong>StatusDrop</strong>': 'Encontre o vídeo do <strong>StatusDrop</strong>',
    '<strong>Tap & hold</strong> the video': '<strong>Toque e segure</strong> o vídeo',
    'Tap <strong>Forward</strong> →\\n              Select <strong>My Status</strong>': 'Toque em <strong>Encaminhar</strong> →\\n              Selecione <strong>Meu Status</strong>',
    '<strong>Done! 🎉</strong>\\n              Enjoy your HD Status!': '<strong>Pronto! 🎉</strong>\\n              Aproveite seu Status em HD!',
    '🔄 Process More Videos': '🔄 Processar Mais Vídeos',
    '📤 Share App': '📤 Compartilhar App',
    '❓ Frequently Asked Questions': '❓ Perguntas Frequentes',
    'Why is my WhatsApp Status video blurry?': 'Por que meu vídeo no WhatsApp Status fica embaçado?',
    'WhatsApp automatically compresses videos to save bandwidth, which destroys quality. StatusDrop pre-compresses your video to the exact specifications WhatsApp expects, so it stays HD.': 'O WhatsApp destrói automaticamente a qualidade do vídeo para economizar largura de banda. O StatusDrop pré-comprime seu vídeo com as especificações exatas que o WhatsApp espera — assim ele continua em HD quando postado como Status.',
    'WhatsApp automatically destroys video quality to save bandwidth.\\n          StatusDrop pre-compresses your video to the exact specs WhatsApp\\n          expects — so it stays HD quality when posted as a Status.': 'O WhatsApp destrói automaticamente a qualidade do vídeo para economizar largura de banda. O StatusDrop pré-comprime seu vídeo com as especificações exatas que o WhatsApp espera — assim ele continua em HD quando postado como Status.',
    'How do I upload a long video to WhatsApp Status?': 'Como envio um vídeo longo para o WhatsApp Status?',
    'WhatsApp Status only allows 29-second videos. StatusDrop automatically splits your long video into multiple 29-second clips and sends them all directly to your WhatsApp for free.': 'O WhatsApp Status só permite vídeos de 29 segundos. O StatusDrop divide automaticamente seu vídeo longo em vários clipes de 29 segundos e envia todos direto pro seu WhatsApp — totalmente de graça!',
    'WhatsApp Status only allows 29-second videos. StatusDrop\\n          automatically splits your long video into multiple 29-second\\n          clips and sends them all directly to your WhatsApp — completely free!': 'O WhatsApp Status só permite vídeos de 29 segundos. O StatusDrop divide automaticamente seu vídeo longo em vários clipes de 29 segundos e envia todos direto pro seu WhatsApp — totalmente de graça!',
    'Is StatusDrop free to use?': 'O StatusDrop é realmente gratuito?',
    'Yes, StatusDrop is completely free. No login, no watermark, no hidden fees. Upload videos up to 300MB and receive them HD quality on WhatsApp.': "Sim! 100% grátis. Sem login, sem conta, sem marca d'água, sem taxas ocultas. Envie vídeos de até 300MB e receba-os em qualidade HD diretamente no WhatsApp.",
    'Is StatusDrop really free?': 'O StatusDrop é realmente gratuito?',
    'Yes! 100% free. No login, no account, no watermark, no hidden\\n          fees. Upload videos up to 300MB and receive them in HD quality\\n          directly on WhatsApp.': "Sim! 100% grátis. Sem login, sem conta, sem marca d'água, sem taxas ocultas. Envie vídeos de até 300MB e receba-os em qualidade HD diretamente no WhatsApp.",
    'What video formats does StatusDrop support?': 'Quais formatos de vídeo são suportados?',
    'What video formats are supported?': 'Quais formatos de vídeo são suportados?',
    'StatusDrop supports MP4, MOV, AVI, MKV, 3GP and WMV formats up to 300MB in size.': 'O StatusDrop suporta os formatos MP4, MOV, AVI, MKV, 3GP e WMV de até 300MB de tamanho de arquivo.',
    'StatusDrop supports MP4, MOV, AVI, MKV, 3GP and WMV\\n          formats up to 300MB in file size.': 'O StatusDrop suporta os formatos MP4, MOV, AVI, MKV, 3GP e WMV de até 300MB de tamanho de arquivo.',
    'Is my video private and secure?': 'O meu vídeo é privado e seguro?',
    'Yes! Your video is automatically deleted from our servers\\n          within 5 minutes after being sent to your WhatsApp.\\n          We never store or share your videos.': 'Sim! Seu vídeo é excluído automaticamente de nossos servidores 5 minutos após ser enviado pro seu WhatsApp. Nunca armazenamos ou compartilhamos seus vídeos.',
    'Free HD WhatsApp Status videos.<br/>\\n        Compress, split & deliver instantly.': 'Vídeos HD grátis pro WhatsApp Status.<br/>\\n        Comprima, divida e entregue na hora.',
    'Privacy Policy': 'Política de Privacidade',
    '🔒 No Account Needed': '🔒 Sem Conta Necessária',
    '🗑️ Auto Deleted in 5 mins': '🗑️ Exclusão Auto em 5 mins',
    '📵 No Watermark': "📵 Sem Marca d'água",
    '© 2026 StatusDrop · Made with 💚': '© 2026 StatusDrop · Feito com 💚'
  },
  es: {
    '<html lang="en">': '<html lang="es">',
    '<link rel="canonical" href="https://www.wastatusvideo.com"/>': '<link rel="canonical" href="https://www.wastatusvideo.com/es/"/>',
    'WhatsApp Status Video Compressor - Upload HD & Long Videos Free': 'WhatsApp Status Video Compressor - Sube Videos Largos y en HD Gratis',
    'Free WhatsApp Status video compressor. Upload HD videos up to 300MB, auto-split long videos into 29-second clips. No blur, no watermark, no login needed. Works worldwide!': 'Compresor gratuito de vídeos para WhatsApp Status. Sube vídeos en HD de hasta 300MB, divide vídeos largos en clips de 29 segundos automáticamente. Sin marcas de agua.',
    'Stop blurry WhatsApp Status videos! Compress & send HD videos directly to your WhatsApp. Auto-splits long videos. 100% Free, No login needed.': '¡No más vídeos borrosos en WhatsApp Status! Comprime y envía vídeos en HD directamente a tu WhatsApp. Divide vídeos largos automáticamente. 100% Gratis.',
    'WhatsApp Status Video Compressor - HD Videos Free': 'WhatsApp Status Video Compressor - Videos HD Gratis',
    'Stop blurry WhatsApp Status! Compress & send HD videos free. Auto-splits long videos into 29s clips.': '¡No más vídeos borrosos! Comprime y envía vídeos en HD gratis. Divide vídeos largos automáticamente en clips de 29s.',
    'Video Compressor\\n    </h1>': 'Compresor de Vídeo\\n    </h1>',
    'Stop blurry Status videos! Upload HD videos up to 300MB —\\n      auto-split into 29s clips & delivered to your WhatsApp free': '¡Basta de vídeos de Estado borrosos! Sube vídeos en HD de hasta 300MB —\\n      divídelos automáticamente en clips de 29s y recíbelos en WhatsApp gratis',
    '✅ Free': '✅ Gratis',
    '⚡ Fast': '⚡ Rápido',
    '🔒 Private': '🔒 Privado',
    '✂️ Auto Split': '✂️ División Auto',
    '🌍 Works Worldwide': '🌍 Funciona en todo el mundo',
    'Videos Processed': 'Vídeos Procesados',
    'Quality Always': 'Calidad Siempre',
    'Max Upload': 'Subida Máxima',
    'Always & Forever': 'Siempre y Para Siempre',
    'Auto Split & Compress — Any Size Video!': 'Dividir y Comprimir — ¡Cualquier Tamaño!',
    'Long videos are automatically split into 29-second WhatsApp-ready clips. Upload up to 300MB!': 'Los vídeos largos se dividen automáticamente en clips de 29s para WhatsApp. ¡Sube hasta 300MB!',
    'Upload Your Videos': 'Sube tus Vídeos',
    'Drop Videos Here': 'Suelta los Vídeos Aquí',
    'or click to browse files': 'o haz clic para buscar archivos',
    'Max 3 videos · 300MB total · Auto-split into 29s clips!': 'Máx 3 vídeos · Total de 300MB · ¡División auto en 29s!',
    '🚀 Compress Videos': '🚀 Comprimir Vídeos',
    'Processing Videos...': 'Procesando Vídeos...',
    'Starting...': 'Iniciando...',
    'Overall Progress': 'Progreso General',
    'Activate on WhatsApp': 'Activar en WhatsApp',
    'Your video was split into <span id="clipCount">?</span> clips — all will be sent to WhatsApp!': 'Tu vídeo se dividió en <span id="clipCount">?</span> clips — ¡todos se enviarán a WhatsApp!',
    'Your Activation Code': 'Tu Código de Activación',
    '📋 Copy Code': '📋 Copiar Código',
    '⏱️ Code expires in:': '⏱️ El código expira en:',
    'Send code before timer runs out!': '¡Envía el código antes de que termine el tiempo!',
    '❌ Code Expired!': '❌ ¡Código Expirado!',
    'Your 5 minutes are up. Please compress your video again.': 'Tus 5 minutos se acabaron. Por favor, comprime tu vídeo de nuevo.',
    '🔄 Start Again': '🔄 Empezar de Nuevo',
    '📋 How it works:': '📋 Cómo funciona:',
    'Click the button below to <strong>open WhatsApp</strong>': 'Haz clic en el botón de abajo para <strong>abrir WhatsApp</strong>',
    'Your activation code is <strong>already typed</strong> in the message': 'Tu código de activación <strong>ya está escrito</strong> en el mensaje',
    'Just press <strong>SEND</strong> in WhatsApp': 'Solo presiona <strong>ENVIAR</strong> en WhatsApp',
    'Receive your <strong>HD video clips</strong> directly in WhatsApp! 🎬': '¡Recibe tus <strong>clips de vídeo en HD</strong> directamente en WhatsApp! 🎬',
    '⚠️ <span>Code valid for <strong>5 minutes only!</strong> Send it on WhatsApp before it expires!</span>': '⚠️ <span>¡Código válido por <strong>solo 5 minutos!</strong> ¡Envíalo en WhatsApp antes de que expire!</span>',
    '💚 Activate on WhatsApp': '💚 Activar en WhatsApp',
    'Almost There! 🚀': '¡Casi Listo! 🚀',
    'Send the activation code in WhatsApp to receive your videos!': '¡Envía el código de activación en WhatsApp para recibir tus vídeos!',
    'Video Sent': 'Vídeo Enviado',
    'Quality\\n              </div>': 'Calidad\\n              </div>',
    'Delivered\\n              </div>': 'Entregado\\n              </div>',
    '📱 Upload to Status:': '📱 Subir al Estado:',
    'Open <strong>WhatsApp</strong>': 'Abre <strong>WhatsApp</strong>',
    'Find video from <strong>StatusDrop</strong>': 'Encuentra el vídeo de <strong>StatusDrop</strong>',
    '<strong>Tap & hold</strong> the video': '<strong>Toca y mantén</strong> presionado el vídeo',
    'Tap <strong>Forward</strong> →\\n              Select <strong>My Status</strong>': 'Toca <strong>Reenviar</strong> →\\n              Selecciona <strong>Mi Estado</strong>',
    '<strong>Done! 🎉</strong>\\n              Enjoy your HD Status!': '<strong>¡Listo! 🎉</strong>\\n              ¡Disfruta tu Estado en HD!',
    '🔄 Process More Videos': '🔄 Procesar Más Vídeos',
    '📤 Share App': '📤 Compartir App',
    '❓ Frequently Asked Questions': '❓ Preguntas Frecuentes',
    'Why is my WhatsApp Status video blurry?': '¿Por qué mi vídeo de WhatsApp Status se ve borroso?',
    'WhatsApp automatically compresses videos to save bandwidth, which destroys quality. StatusDrop pre-compresses your video to the exact specifications WhatsApp expects, so it stays HD.': 'WhatsApp destruye automáticamente la calidad del vídeo para ahorrar ancho de banda. StatusDrop precomprime tu vídeo con las especificaciones exactas que WhatsApp espera, por lo que se mantiene en calidad HD cuando se publica como un Estado.',
    'WhatsApp automatically destroys video quality to save bandwidth.\\n          StatusDrop pre-compresses your video to the exact specs WhatsApp\\n          expects — so it stays HD quality when posted as a Status.': 'WhatsApp destruye automáticamente la calidad del vídeo para ahorrar ancho de banda. StatusDrop precomprime tu vídeo con las especificaciones exactas que WhatsApp espera, por lo que se mantiene en calidad HD cuando se publica como un Estado.',
    'How do I upload a long video to WhatsApp Status?': '¿Cómo subo un vídeo largo a WhatsApp Status?',
    'WhatsApp Status only allows 29-second videos. StatusDrop automatically splits your long video into multiple 29-second clips and sends them all directly to your WhatsApp for free.': 'WhatsApp Status solo permite vídeos de 29 segundos. StatusDrop divide automáticamente tu vídeo largo en varios clips de 29 segundos y los envía todos directamente a tu WhatsApp, ¡completamente gratis!',
    'WhatsApp Status only allows 29-second videos. StatusDrop\\n          automatically splits your long video into multiple 29-second\\n          clips and sends them all directly to your WhatsApp — completely free!': 'WhatsApp Status solo permite vídeos de 29 segundos. StatusDrop divide automáticamente tu vídeo largo en varios clips de 29 segundos y los envía todos directamente a tu WhatsApp, ¡completamente gratis!',
    'Is StatusDrop free to use?': '¿StatusDrop es realmente gratis?',
    'Yes, StatusDrop is completely free. No login, no watermark, no hidden fees. Upload videos up to 300MB and receive them HD quality on WhatsApp.': '¡Sí! 100% gratis. Sin iniciar sesión, sin cuenta, sin marca de agua, sin tarifas ocultas. Sube vídeos de hasta 300MB y recíbelos en calidad HD directamente en WhatsApp.',
    'Is StatusDrop really free?': '¿StatusDrop es realmente gratis?',
    'Yes! 100% free. No login, no account, no watermark, no hidden\\n          fees. Upload videos up to 300MB and receive them in HD quality\\n          directly on WhatsApp.': '¡Sí! 100% gratis. Sin iniciar sesión, sin cuenta, sin marca de agua, sin tarifas ocultas. Sube vídeos de hasta 300MB y recíbelos en calidad HD directamente en WhatsApp.',
    'What video formats does StatusDrop support?': '¿Qué formatos de vídeo son compatibles?',
    'What video formats are supported?': '¿Qué formatos de vídeo son compatibles?',
    'StatusDrop supports MP4, MOV, AVI, MKV, 3GP and WMV formats up to 300MB in size.': 'StatusDrop admite los formatos MP4, MOV, AVI, MKV, 3GP y WMV de hasta 300 MB de tamaño de archivo.',
    'StatusDrop supports MP4, MOV, AVI, MKV, 3GP and WMV\\n          formats up to 300MB in file size.': 'StatusDrop admite los formatos MP4, MOV, AVI, MKV, 3GP y WMV de hasta 300 MB de tamaño de archivo.',
    'Is my video private and secure?': '¿Mi vídeo es privado y seguro?',
    'Yes! Your video is automatically deleted from our servers\\n          within 5 minutes after being sent to your WhatsApp.\\n          We never store or share your videos.': '¡Sí! Tu vídeo se elimina automáticamente de nuestros servidores 5 minutos después de enviarse a tu WhatsApp. Nunca almacenamos ni compartimos tus vídeos.',
    'Free HD WhatsApp Status videos.<br/>\\n        Compress, split & deliver instantly.': 'Vídeos HD gratis para WhatsApp Status.<br/>\\n        Comprime, divide y entrega al instante.',
    'Privacy Policy': 'Política de Privacidad',
    '🔒 No Account Needed': '🔒 No Necesita Cuenta',
    '🗑️ Auto Deleted in 5 mins': '🗑️ Eliminación Auto en 5 mins',
    '📵 No Watermark': '📵 Sin Marca de Agua',
    '© 2026 StatusDrop · Made with 💚': '© 2026 StatusDrop · Hecho con 💚'
  }
};

for (const lang of ['hi', 'pt', 'es']) {
  let translatedHtml = indexHtml;
  for (const [eng, loc] of Object.entries(translations[lang])) {
    // using split join replaces all occurrences without regex escaping issues
    translatedHtml = translatedHtml.split(eng).join(loc);
  }
  const dirPath = path.join(__dirname, 'public', lang);
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
  fs.writeFileSync(path.join(dirPath, 'index.html'), translatedHtml);
}

console.log("Translation complete");
